"use client";
import styles from "./chartHighlightSection.module.css";
import Image from "next/image";
import Link from "next/link";
import { useAppSelector } from "@/lib/hooks";
const ChartHighlightSection: React.FC = () => {
  const { currentUser } = useAppSelector((store) => {
    return store.auth;
  });
  return (
    <section className={styles.highlight}>
      <div className={styles.highlightWrapper}>
        <div className={styles.imageArea}>
          <Image
            src="/illustrations/charts.png"
            alt="charts generated by ChartGee"
            fill
            className={styles.image}
          />
        </div>
        <div className={styles.contentArea}>
          <p className={styles.slogan}>START BUILDING YOUR DATA STORY</p>
          <h1 className={styles.title}>
            Professional charts for effective communication
          </h1>
          <p className={styles.description}>
            A powerful presentation starts with a clear chart. With ChartGee,
            you can visualize your data beautifully and make a lasting
            impression. Build trust, clarity, and confidence with charts that
            speak for themselves.
          </p>
          <div className={styles.BTNwrapper}>
            <Link
              href={currentUser ? "/dashboard" : "/signup"}
              className={styles.BTN}
            >
              Get Started Now
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
};

export default ChartHighlightSection;
